site_name: SkInnervation3D App
site_url: https://reimann-lab.github.io/skinnervation3d-app
site_description: User interface to run Fractal task-based image analysis workflows.
site_author: Giliane Rochat
repo_url: https://github.com/reimann-lab/skinnervation3d-app
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - content.code.annotate
  palette:

    # Palette toggle for light mode
    - scheme: default 
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: light blue
      accent: indigo

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: indigo
      accent: light blue
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md

plugins:
  - search
  #- offline
  #- print-site:
  #    add_table_of_contents: true
  #    toc_depth: 3
  #    toc_title: "Index"
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google